# Cox Proportional Hazard Modeling 2: Gene Expression 
Now, we will do univariate testing of individual gene expression to see which effect survival the most

In [21]:
import pandas as pd
import numpy as np
from lifelines import CoxPHFitter
import pyhere as here

In [3]:
here.here()

PosixPath('/Users/jmakings/Documents/Projects/breast_cancer_survival_prediction')

### Preprocessing Functions

In [4]:
def preprocess_for_cox(df, duration_col, event_col):
    # Drop rows with missing values in duration or event columns
    df = df.dropna(subset=[duration_col, event_col])
    
    # Ensure duration column is numeric
    df[duration_col] = pd.to_numeric(df[duration_col], errors='coerce')
    
    # Drop rows with non-numeric duration values
    df = df.dropna(subset=[duration_col])
    
    return df

In [5]:
# converts float columns with whole numbers to integer type
def convert_whole_float_columns_to_int(df):
    for col in df.columns:
        if pd.api.types.is_float_dtype(df[col]):
            # Check if all non-null values are whole numbers
            if df[col].dropna().apply(float.is_integer).all():
                df[col] = df[col].astype("Int64")  # nullable integer type
    return df

In [6]:
def one_hot_encode(df, convert_whole_num_ints=True):
    # One hot encode categorical variables

    # Identify categorical columns automatically
    cat_cols = df.select_dtypes(include=["object", "category"]).columns

    # Apply one-hot encoding only to categorical columns
    df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)

    # Change boolean columns to integers
    bool_cols = df_encoded.select_dtypes(include=["bool"]).columns
    df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)
    
    if convert_whole_num_ints:
        df_encoded = convert_whole_float_columns_to_int(df_encoded)
    return df_encoded

### Load data and Preprocess

In [7]:
# load clinical metadata with PCA + UMAP features
pca_clinical_df = pd.read_csv(here.here("data", "processed","clinical_dimred_features.csv"))

In [8]:
# load expression data
expression_data_df = pd.read_csv(here.here("data", "processed","expression_data.csv"))

In [9]:
# One hot encode categorical variables

df_encoded = one_hot_encode(pca_clinical_df)
df_encoded = convert_whole_float_columns_to_int(df_encoded)
# Rename for clarity
df_encoded = df_encoded.rename(columns={
    "overall_survival_months": "time",
    "death_from_cancer_Living": "event"
})

In [16]:
# gene expression data with time and cancer survival columns
survival_exp = pd.concat([df_encoded[["time","event"]], expression_data_df], axis=1)

# Ensure no time = 0 for proportional hazards testing
EPS = 1e-4  # or smaller if time is in months
survival_exp['time_adj'] = survival_exp['time'].clip(lower=EPS)

#### Time = 0 will cause runtime error when log-transforming, so we clip it to a very small number

In [18]:
(survival_exp['time']==0).sum()

1

In [17]:
(survival_exp['time_adj']==0).sum()

0

## Screen Genes Individually for Cox Modeling

We will look at each gene individually first, observing which genes violate our proportional hazard assumption

In [19]:
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test

ph_results = []

for gene in expression_data_df.columns:
    print(f"Processing gene: {gene}")
    df_tmp = survival_exp[['time_adj', 'event', gene]].dropna()

    # Skip genes with near-zero variance
    if df_tmp[gene].std() < 1e-6:
        continue

    cph = CoxPHFitter()
    cph.fit(df_tmp, 'time_adj', 'event')

    # Perform proportional hazards test on log time to model early vs late effects better
    ph_test = proportional_hazard_test(cph, df_tmp, time_transform='log')

    ph_results.append({
        'gene': gene,
        'ph_p': ph_test.summary.loc[gene, 'p'],
        'coef': cph.params_[gene],
        'hr': cph.hazard_ratios_[gene],
    })

ph_df = pd.DataFrame(ph_results)
ph_df['ph_violation'] = ph_df['ph_p'] < 0.01

Processing gene: brca1
Processing gene: brca2
Processing gene: palb2
Processing gene: pten
Processing gene: tp53
Processing gene: atm
Processing gene: cdh1
Processing gene: chek2
Processing gene: nbn
Processing gene: nf1
Processing gene: stk11
Processing gene: bard1
Processing gene: mlh1
Processing gene: msh2
Processing gene: msh6
Processing gene: pms2
Processing gene: epcam
Processing gene: rad51c
Processing gene: rad51d
Processing gene: rad50
Processing gene: rb1
Processing gene: rbl1
Processing gene: rbl2
Processing gene: ccna1
Processing gene: ccnb1
Processing gene: cdk1
Processing gene: ccne1
Processing gene: cdk2
Processing gene: cdc25a
Processing gene: ccnd1
Processing gene: cdk4
Processing gene: cdk6
Processing gene: ccnd2
Processing gene: cdkn2a
Processing gene: cdkn2b
Processing gene: myc
Processing gene: cdkn1a
Processing gene: cdkn1b
Processing gene: e2f1
Processing gene: e2f2
Processing gene: e2f3
Processing gene: e2f4
Processing gene: e2f5
Processing gene: e2f6
Processing gene: e2f7
Processing gene: e2f8
Processing gene: src
Processing gene: jak1
Processing gene: jak2
Processing gene: stat1
Processing gene: stat2
Processing gene: stat3
Processing gene: stat5a
Processing gene: stat5b
Processing gene: mdm2
Processing gene: tp53bp1
Processing gene: adam10
Processing gene: adam17
Processing gene: aph1a
Processing gene: aph1b
Processing gene: arrdc1
Processing gene: cir1
Processing gene: ctbp1
Processing gene: ctbp2
Processing gene: cul1
Processing gene: dll1
Processing gene: dll3
Processing gene: dll4
Processing gene: dtx1
Processing gene: dtx2
Processing gene: dtx3
Processing gene: dtx4
Processing gene: ep300
Processing gene: fbxw7
Processing gene: hdac1
Processing gene: hdac2
Processing gene: hes1
Processing gene: hes5
Processing gene: heyl
Processing gene: itch
Processing gene: jag1
Processing gene: jag2
Processing gene: kdm5a
Processing gene: lfng
Processing gene: maml1
Processing gene: maml2
Processing gene: maml3
Processing gene: ncor2
Processing gene: ncstn
Processing gene: notch1
Processing gene: notch2
Processing gene: notch3
Processing gene: nrarp
Processing gene: numb
Processing gene: numbl
Processing gene: psen1
Processing gene: psen2
Processing gene: psenen
Processing gene: rbpj
Processing gene: rbpjl
Processing gene: rfng
Processing gene: snw1
Processing gene: spen
Processing gene: hes2
Processing gene: hes4
Processing gene: hes7
Processing gene: hey1
Processing gene: hey2
Processing gene: acvr1
Processing gene: acvr1b
Processing gene: acvr1c
Processing gene: acvr2a
Processing gene: acvr2b
Processing gene: acvrl1
Processing gene: akt1
Processing gene: akt1s1
Processing gene: akt2
Processing gene: apaf1
Processing gene: arl11
Processing gene: atr
Processing gene: aurka
Processing gene: bad
Processing gene: bcl2
Processing gene: bcl2l1
Processing gene: bmp10
Processing gene: bmp15
Processing gene: bmp2
Processing gene: bmp3
Processing gene: bmp4
Processing gene: bmp5
Processing gene: bmp6
Processing gene: bmp7
Processing gene: bmpr1a
Processing gene: bmpr1b
Processing gene: bmpr2
Processing gene: braf
Processing gene: casp10
Processing gene: casp3
Processing gene: casp6
Processing gene: casp7
Processing gene: casp8
Processing gene: casp9
Processing gene: chek1
Processing gene: csf1
Processing gene: csf1r
Processing gene: cxcl8
Processing gene: cxcr1
Processing gene: cxcr2
Processing gene: dab2
Processing gene: diras3
Processing gene: dlec1
Processing gene: dph1
Processing gene: egfr
Processing gene: eif4e
Processing gene: eif4ebp1
Processing gene: eif5a2
Processing gene: erbb2
Processing gene: erbb3
Processing gene: erbb4
Processing gene: fas
Processing gene: fgf1
Processing gene: fgfr1
Processing gene: folr1
Processing gene: folr2
Processing gene: folr3
Processing gene: foxo1
Processing gene: foxo3
Processing gene: gdf11
Processing gene: gdf2
Processing gene: gsk3b
Processing gene: hif1a
Processing gene: hla-g
Processing gene: hras
Processing gene: igf1
Processing gene: igf1r
Processing gene: inha
Processing gene: inhba
Processing gene: inhbc
Processing gene: itgav
Processing gene: itgb3
Processing gene: izumo1r
Processing gene: kdr
Processing gene: kit
Processing gene: kras
Processing gene: map2k1
Processing gene: map2k2
Processing gene: map2k3
Processing gene: map2k4
Processing gene: map2k5
Processing gene: map3k1
Processing gene: map3k3
Processing gene: map3k4
Processing gene: map3k5
Processing gene: mapk1
Processing gene: mapk12
Processing gene: mapk14
Processing gene: mapk3
Processing gene: mapk4
Processing gene: mapk6
Processing gene: mapk7
Processing gene: mapk8
Processing gene: mapk9
Processing gene: mdc1
Processing gene: mlst8
Processing gene: mmp1
Processing gene: mmp10
Processing gene: mmp11
Processing gene: mmp12
Processing gene: mmp13
Processing gene: mmp14
Processing gene: mmp15
Processing gene: mmp16
Processing gene: mmp17
Processing gene: mmp19
Processing gene: mmp2
Processing gene: mmp21
Processing gene: mmp23b
Processing gene: mmp24
Processing gene: mmp25
Processing gene: mmp26
Processing gene: mmp27
Processing gene: mmp28
Processing gene: mmp3
Processing gene: mmp7
Processing gene: mmp9
Processing gene: mtor
Processing gene: nfkb1
Processing gene: nfkb2
Processing gene: opcml
Processing gene: pdgfa
Processing gene: pdgfb
Processing gene: pdgfra
Processing gene: pdgfrb
Processing gene: pdpk1
Processing gene: peg3
Processing gene: pik3ca
Processing gene: pik3r1
Processing gene: pik3r2
Processing gene: plagl1
Processing gene: ptk2
Processing gene: rab25
Processing gene: rad51
Processing gene: raf1
Processing gene: rassf1
Processing gene: rheb
Processing gene: rictor
Processing gene: rps6
Processing gene: rps6ka1
Processing gene: rps6ka2
Processing gene: rps6kb1
Processing gene: rps6kb2
Processing gene: rptor
Processing gene: slc19a1
Processing gene: smad1
Processing gene: smad2
Processing gene: smad3
Processing gene: smad4
Processing gene: smad5
Processing gene: smad6
Processing gene: smad7
Processing gene: smad9
Processing gene: sptbn1
Processing gene: terc
Processing gene: tert
Processing gene: tgfb1
Processing gene: tgfb2
Processing gene: tgfb3
Processing gene: tgfbr1
Processing gene: tgfbr2
Processing gene: tgfbr3
Processing gene: tsc1
Processing gene: tsc2
Processing gene: vegfa
Processing gene: vegfb
Processing gene: wfdc2
Processing gene: wwox
Processing gene: zfyve9
Processing gene: arid1a
Processing gene: arid1b
Processing gene: cbfb
Processing gene: gata3
Processing gene: kmt2c
Processing gene: kmt2d
Processing gene: myh9
Processing gene: ncor1
Processing gene: pde4dip
Processing gene: ptprd
Processing gene: ros1
Processing gene: runx1
Processing gene: tbx3
Processing gene: abcb1
Processing gene: abcb11
Processing gene: abcc1
Processing gene: abcc10
Processing gene: bbc3
Processing gene: bmf
Processing gene: cyp2c8
Processing gene: cyp3a4
Processing gene: fgf2
Processing gene: fn1
Processing gene: map2
Processing gene: map4
Processing gene: mapt
Processing gene: nr1i2
Processing gene: slco1b3
Processing gene: tubb1
Processing gene: tubb4a
Processing gene: tubb4b
Processing gene: twist1
Processing gene: adgra2
Processing gene: afdn
Processing gene: aff2
Processing gene: agmo
Processing gene: agtr2
Processing gene: ahnak
Processing gene: ahnak2
Processing gene: akap9
Processing gene: alk
Processing gene: apc
Processing gene: arid2
Processing gene: arid5b
Processing gene: asxl1
Processing gene: asxl2
Processing gene: bap1
Processing gene: bcas3
Processing gene: birc6
Processing gene: cacna2d3
Processing gene: ccnd3
Processing gene: chd1
Processing gene: clk3
Processing gene: clrn2
Processing gene: col12a1
Processing gene: col22a1
Processing gene: col6a3
Processing gene: ctcf
Processing gene: ctnna1
Processing gene: ctnna3
Processing gene: dnah11
Processing gene: dnah2
Processing gene: dnah5
Processing gene: dtwd2
Processing gene: fam20c
Processing gene: fanca
Processing gene: fancd2
Processing gene: flt3
Processing gene: foxp1
Processing gene: frmd3
Processing gene: gh1
Processing gene: gldc
Processing gene: gpr32
Processing gene: gps2
Processing gene: hdac9
Processing gene: herc2
Processing gene: hist1h2bc
Processing gene: kdm3a
Processing gene: kdm6a
Processing gene: klrg1
Processing gene: l1cam
Processing gene: lama2
Processing gene: lamb3
Processing gene: large1
Processing gene: ldlrap1
Processing gene: lifr
Processing gene: lipi
Processing gene: magea8
Processing gene: map3k10
Processing gene: map3k13
Processing gene: men1
Processing gene: mtap
Processing gene: muc16
Processing gene: myo1a
Processing gene: myo3a
Processing gene: ncoa3
Processing gene: nek1
Processing gene: nf2
Processing gene: npnt
Processing gene: nr2f1
Processing gene: nr3c1
Processing gene: nras
Processing gene: nrg3
Processing gene: nt5e
Processing gene: or6a2
Processing gene: palld
Processing gene: pbrm1
Processing gene: ppp2cb
Processing gene: ppp2r2a
Processing gene: prkacg
Processing gene: prkce
Processing gene: prkcq
Processing gene: prkcz
Processing gene: prkg1
Processing gene: prps2
Processing gene: prr16
Processing gene: ptpn22
Processing gene: ptprm
Processing gene: rasgef1b
Processing gene: rpgr
Processing gene: ryr2
Processing gene: sbno1
Processing gene: setd1a
Processing gene: setd2
Processing gene: setdb1
Processing gene: sf3b1
Processing gene: sgcd
Processing gene: shank2
Processing gene: siah1
Processing gene: sik1
Processing gene: sik2
Processing gene: smarcb1
Processing gene: smarcc1
Processing gene: smarcc2
Processing gene: smarcd1
Processing gene: spaca1
Processing gene: stab2
Processing gene: stmn2
Processing gene: syne1
Processing gene: taf1
Processing gene: taf4b
Processing gene: tbl1xr1
Processing gene: tg
Processing gene: thada
Processing gene: thsd7a
Processing gene: ttyh1
Processing gene: ubr5
Processing gene: ush2a
Processing gene: usp9x
Processing gene: utrn
Processing gene: zfp36l1
Processing gene: ackr3
Processing gene: akr1c1
Processing gene: akr1c2
Processing gene: akr1c3
Processing gene: akr1c4
Processing gene: akt3
Processing gene: ar
Processing gene: bche
Processing gene: cdk8
Processing gene: cdkn2c
Processing gene: cyb5a
Processing gene: cyp11a1
Processing gene: cyp11b2
Processing gene: cyp17a1
Processing gene: cyp19a1
Processing gene: cyp21a2
Processing gene: cyp3a43
Processing gene: cyp3a5
Processing gene: cyp3a7
Processing gene: ddc
Processing gene: hes6
Processing gene: hsd17b1
Processing gene: hsd17b10
Processing gene: hsd17b11
Processing gene: hsd17b12
Processing gene: hsd17b13
Processing gene: hsd17b14
Processing gene: hsd17b2
Processing gene: hsd17b3
Processing gene: hsd17b4
Processing gene: hsd17b6
Processing gene: hsd17b7
Processing gene: hsd17b8
Processing gene: hsd3b1
Processing gene: hsd3b2
Processing gene: hsd3b7
Processing gene: mecom
Processing gene: met
Processing gene: ncoa2
Processing gene: nrip1
Processing gene: pik3r3
Processing gene: prkci
Processing gene: prkd1
Processing gene: ran
Processing gene: rdh5
Processing gene: sdc4
Processing gene: serpini1
Processing gene: shbg
Processing gene: slc29a1
Processing gene: sox9
Processing gene: spry2
Processing gene: srd5a1
Processing gene: srd5a2
Processing gene: srd5a3
Processing gene: st7
Processing gene: star
Processing gene: tnk2
Processing gene: tulp4
Processing gene: ugt2b15
Processing gene: ugt2b17
Processing gene: ugt2b7

### Create time interactions for genes violating porportional hazard

In [23]:
# create interaction terms for genes with proportional hazards violations
violating_genes = ph_df.loc[ph_df.ph_violation, 'gene'].tolist()

df_model = survival_exp.copy()

for gene in violating_genes:
    df_model[f'{gene}_logt'] = df_model[gene] * np.log(df_model['time_adj'])

In [ ]:
# 23 genes with proportional hazards violations
len(violating_genes)

23

In [24]:
df_model

,time,event,brca1,brca2,palb2,pten,tp53,atm,cdh1,chek2,...,pdgfa_logt,ptk2_logt,asxl1_logt,asxl2_logt,fancd2_logt,sf3b1_logt,smarcc1_logt,tbl1xr1_logt,ubr5_logt,rdh5_logt
0,140.500000,1,-1.3990,-0.5738,-1.6217,1.4524,0.3504,1.1517,0.0348,0.1266,...,5.113345,-7.865847,3.155537,-7.026645,-10.373067,0.050936,-1.329272,-1.182894,-7.941509,24.779940
1,84.633333,1,-1.3800,0.2777,-1.2154,0.5296,-0.0136,-0.2659,1.3594,0.7961,...,-1.529448,-3.395765,-1.104256,3.436598,-3.155208,11.189025,-5.952242,-0.407439,2.267542,-2.812569
2,163.700000,0,0.0670,-0.8426,0.2114,-0.3326,0.5141,-0.0803,1.1398,0.4187,...,-7.105132,-5.400859,-9.624581,-11.698972,-3.140900,-3.358586,1.260234,-2.098861,2.514861,-3.851056
3,164.933333,1,0.6744,-0.5428,-1.6592,0.6369,1.6708,-0.8880,1.2491,-1.1889,...,-2.131564,13.421958,-8.654403,-9.022002,-1.472949,-3.163904,-3.526397,-2.263286,8.204094,-6.384479
4,41.366667,0,1.2932,-0.9039,-0.7219,0.2168,0.3484,0.3897,0.9131,0.9356,...,-4.481116,11.506916,-2.855883,-3.802136,-2.167970,3.872119,3.291041,-1.244796,11.544141,4.828423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,196.866667,1,0.1563,0.5543,-0.6149,0.4572,1.3822,-0.0537,-0.1323,0.2837,...,-0.983606,-6.882076,-4.802345,-4.372347,-1.297389,7.771653,0.864750,0.867391,-2.859960,-3.422021
1900,44.733333,0,0.1343,0.9128,1.3017,0.7383,0.1841,0.0028,0.1243,2.2040,...,-5.982712,-0.966903,-8.173066,0.521079,10.754514,-1.010611,-2.370128,-1.218510,1.063821,-2.386091
1901,175.966667,0,1.8107,-0.2608,0.4006,-0.2985,0.0356,-0.1620,1.5486,1.5309,...,-7.355778,-11.999220,-10.570667,-5.262326,0.414141,5.470689,3.881340,0.783817,4.545206,-8.460670
1902,86.233333,0,-1.2746,-1.7695,-0.3454,-0.3850,0.6689,1.4531,1.0956,-0.0948,...,-3.617347,-2.729502,-8.075296,-1.265804,-3.454219,7.010059,-1.525651,6.115528,-4.444131,-3.804544
1903,201.900000,0,-0.7525,0.7352,0.6448,-0.3241,-0.0434,1.7272,0.7193,3.1425,...,-6.989806,-1.482992,3.218633,0.556785,-4.432521,2.644332,-13.992350,1.316328,0.745211,-5.205333

### Create new model with all genes, including time covariates for genes violating PH

In [ ]:
# create interaction terms for genes with proportional hazards violations
violating_genes = ph_df.loc[ph_df.ph_violation, 'gene'].tolist()

df_model = survival_exp.copy()

for gene in violating_genes:
    df_model[f'{gene}_logt'] = df_model[gene] * np.log(df_model['time_adj'])

# Define model variables
base_genes = ph_df.loc[
    (ph_df.ph_violation == False) & (ph_df.ph_p > 0.05),
    'gene'
].tolist()

# genes without proportional hazards violations
len(base_genes)

435

In [ ]:
# create covariates list, combining base genes, violating genes, and their interaction terms
covariates = (
    base_genes +
    violating_genes +
    [f'{g}_logt' for g in violating_genes]
)

In [ ]:
# fit new model with interaction terms
# penalizer and l1_ratio are set to balance model complexity and avoid overfitting
cph = CoxPHFitter(penalizer=0.1, l1_ratio=0.5)
cph.fit(
    df_model[['time_adj', 'event'] + covariates],
    'time_adj',
    'event'
)

In [31]:
cph.print_summary()

<lifelines.CoxPHFitter: fitted with 1904 total observations, 1103 right-censored observations>
             duration col = 'time_adj'
                event col = 'event'
                penalizer = 0.1
                 l1 ratio = 0.5
      baseline estimation = breslow
   number of observations = 1904
number of events observed = 801
   partial log-likelihood = -4880.47
         time fit was run = 2025-12-23 23:11:14 UTC

---
              coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
brca1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
brca2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
pten         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
tp53          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdh1         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
chek2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
nbn           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bard1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mlh1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
msh2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
msh6          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
pms2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
epcam         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rad51c        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rad51d        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rad50         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rb1           0.03      1.03      0.04           -0.05            0.12                0.95                1.12
rbl1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ccna1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ccnb1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdk1         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ccne1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdc25a        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ccnd1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdk4          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdk6          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ccnd2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdkn2a        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cdkn2b        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
myc           0.05      1.05      0.04           -0.03            0.13                0.97                1.14
cdkn1b        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f3          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f4         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f5          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f6          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f7         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
e2f8         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
src          -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
jak1          0.06      1.06      0.05           -0.03            0.15                0.97                1.16
jak2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
stat1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
stat2        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
stat3         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
stat5a        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
stat5b       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
adam10        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
adam17        0.04      1.04      0.04           -0.04            0.11                0.96                1.12
aph1a        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
aph1b        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
arrdc1       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cir1         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ctbp1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cul1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dll3          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dll4          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dtx1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dtx2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dtx3         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dtx4          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ep300         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
fbxw7         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hdac1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hdac2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hes1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hes5         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
heyl         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
itch         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
jag1         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
jag2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
kdm5a         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
lfng         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
maml2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
maml3        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ncor2        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
ncstn        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
notch1        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
notch2        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
nrarp         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
numb         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
numbl         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
psen2        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
psenen        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rbpjl        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
rfng          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
snw1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
spen          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hes2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hes4         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hes7         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hey1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hey2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvr1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvr1b        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvr1c        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvr2a       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvr2b       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
acvrl1        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
akt1         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
akt1s1       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
akt2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
apaf1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
arl11        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
atr           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
aurka         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bad           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bcl2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bcl2l1       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp10        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp15        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp2          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp4          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp5         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmp6          0.02      1.02      0.04           -0.06            0.09                0.95                1.09
bmp7         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmpr1b       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
bmpr2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
braf         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
casp3         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
casp6         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
casp7         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
casp9         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
chek1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cxcl8         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
cxcr1         0.05      1.06      0.04           -0.02            0.13                0.98                1.14
cxcr2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dab2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
diras3       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dlec1        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dph1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
egfr          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
eif4e         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
eif4ebp1     -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
eif5a2       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
erbb2         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
erbb3        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
erbb4        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
fas           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
fgf1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
fgfr1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
folr1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
folr3         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
foxo1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
foxo3         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
gdf11         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
gdf2         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
gsk3b        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hif1a         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hla-g         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
hras         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
igf1          0.00      1.00      0.00           -0.00            0.00                1.00                1.00
igf1r        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
inha         -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
inhba         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
itgav         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
itgb3         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
izumo1r      -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
kdr           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
kit           0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map2k1        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map2k2       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map2k3        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map2k4       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map2k5       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map3k1       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map3k3       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map3k4       -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
map3k5        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk1         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk12        0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk3        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk4         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk6         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk7         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
mapk8        -0.00      1.00      0.00           -0.00            0.00                1.00                1.00

### Model Result
Many genes given coefficient of 0 due to L1 regularization.

### Next steps: 
1. Tune penalizer via k-fold cross validation with an array of penalizer values

In [32]:
from lifelines.utils import k_fold_cross_validation

for p in [0.001, 0.01, 0.05, 0.1]:
    cph = CoxPHFitter(penalizer=p, l1_ratio=0.5)
    scores = k_fold_cross_validation(
        cph,
        df_model[['time_adj', 'event'] + covariates],
        duration_col='time_adj',
        event_col='event',
        k=5,
        scoring_method="concordance_index"
    )
    print(p, np.mean(scores))

0.001 0.667591670559224
0.01 0.680085385054688

/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.04604e-16): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=7.99568e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=5.10617e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.92898e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.02374e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.32615e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.78554e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.37053e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.05497e-17): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=8.11785e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=6.25598e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=5.72927e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.42208e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.41954e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.65786e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.04651e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.59999e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.26627e-18): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=9.28097e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=7.24106e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=5.7104e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.57881e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.74938e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.78357e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.35856e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.42693e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.0986e-19): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=6.1052e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.69773e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.62331e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.24035e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.5096e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.94924e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.52732e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.19041e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.02395e-20): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=6.51786e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=5.03083e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.89309e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.02444e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.35243e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.72468e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.36975e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.05081e-21): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=8.06871e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=6.20095e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.76852e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.27763e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.75247e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.34649e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.65662e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.27588e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=9.84013e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.62739e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.55313e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.71374e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.06464e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.58752e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.22144e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=9.39644e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=7.22475e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=7.21677e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=5.52358e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=4.23628e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=3.21809e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.47581e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.45338e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.12329e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.37876e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.17948e-24): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=8.84325e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=6.75914e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.87844e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=2.21445e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.70635e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)
/Users/jmakings/miniconda3/envs/bc_survival/lib/python3.11/site-packages/scipy/_lib/_util.py:1226: LinAlgWarning: Ill-conditioned matrix (rcond=1.29914e-25): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

0.05 0.7025629447900245
0.1 0.6856797684341873